[package]
name = "moete-web"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
axum = "0.8.7"
moete-core = { path = "../moete-core" }
tokio.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
